export const mockData = [
  {
    affiliateName: "Gy Test",
    flag: "Contains Leaks",
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 356.05,
    paidPayouts: 0.0,
    unpaidPayouts: 35.61,
    readyPayouts: 35.61,
    payoutType: "Cash",
  },
  {
    affiliateName: "Dwight Wisoky",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 267.04,
    paidPayouts: 0.0,
    unpaidPayouts: 26.7,
    readyPayouts: 0.0,
    payoutType: "Store Credit",
  },
  {
    affiliateName: "Zack Treutel",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 161.96,
    paidPayouts: 0.0,
    unpaidPayouts: 16.2,
    readyPayouts: 16.2,
    payoutType: "Store Credit",
  },
  {
    affiliateName: "Hilma Welch",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 126.93,
    paidPayouts: 0.0,
    unpaidPayouts: 12.69,
    readyPayouts: 0.0,
    payoutType: "Cash",
  },
  {
    affiliateName: "Ericka Mohr",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 118.84,
    paidPayouts: 0.0,
    unpaidPayouts: 11.88,
    readyPayouts: 11.88,
    payoutType: "Cash",
  },
  {
    affiliateName: "Adam Kohler",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 99.69,
    paidPayouts: 0.0,
    unpaidPayouts: 9.97,
    readyPayouts: 0.0,
    payoutType: "Store Credit",
  },
  {
    affiliateName: "Pierre Crooks",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 97.28,
    paidPayouts: 0.0,
    unpaidPayouts: 9.73,
    readyPayouts: 0.0,
    payoutType: "Store Credit",
  },
  {
    affiliateName: "Rocio West",
    flag: null,
    mostRecentReferral: new Date(2022, 10, 28),
    revenueGenerated: 85.56,
    paidPayouts: 0.0,
    unpaidPayouts: 8.56,
    readyPayouts: 0.0,
    payoutType: "Cash",
  },
];
